CREATE TABLE COMPANY_ACCOUNT (
  ID bigint NOT NULL AUTO_INCREMENT,
  CASH_BALANCE decimal(10,2) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE COMPANY (
  ID bigint NOT NULL AUTO_INCREMENT,
  NAME varchar(200) NOT NULL,
  COMPANY_ACCOUNT_ID bigint UNIQUE NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (COMPANY_ACCOUNT_ID) REFERENCES COMPANY_ACCOUNT(ID)
);

CREATE TABLE COMPANY_ROLE (
  ID bigint NOT NULL AUTO_INCREMENT,
  COMPANY_ID bigint NOT NULL,
  USER_ID bigint UNIQUE NOT NULL,
  ROLE varchar(200) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(ID),
  FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);