CREATE TABLE COMPANY_DOCUMENT (
  ID bigint NOT NULL AUTO_INCREMENT,
  COMPANY_ACCOUNT_ID bigint NOT NULL,
  DOCUMENT_ID bigint NOT NULL,
  POINTS_PRICE bigint NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (COMPANY_ACCOUNT_ID) REFERENCES COMPANY_ACCOUNT(ID),
  FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT(ID)
);